<!--=================== Main Content Container ===================-->
<main class="collection-page">
    <section class="breadcrumb-container paira-margin-bottom-3">
        <div class=" breadcrumb"
            style="background: linear-gradient(#070606b3, rgba(30, 23, 23, 0)) ,url(<?= base_url() ?>assets/images/banner/home-banner-big.jpg); ">
            <div class="container-fluid padding-fix">

                <ul class="list-inline text-center" style="padding-top: 100px; padding-bottom: 100px;">
                    <h1 class="" style="color:white;">Terms And Conditions</h1>
                    <li><a href="<?= base_url() ?>" style="font-size: larger;color: white;">Home <i
                                class="fa fa-angle-right"></i></a>
                    </li>
                    <li class="" style="color:#c66b15;">Terms And Conditions</li>
                </ul>
            </div>
        </div>
    </section>
    <section class="latest-picture paira-margin-bottom-3">
        <div class="margin-bottom-40">
        <div class="container">
                    <div class="row">
                        <div class="col-md-12 heading-title margin-bottom-40">
                            <h2 class="text-capitalize margin-clear text-center "><span>TERMS AND CONDITIONS</span></h2>
                        </div>
                          <article id="post-3" class="post-3 page type-page status-publish hentry ">
                                <div class="col-xs-12 col-lg-12 col-sm-12 col-md-12">
                                    <h6 class="text-capitalize margin-clear "> Please read the creative hands of india.com terms of use before purchasing any
                                        products or services offered by the website. You are accessing, browsing,
                                        purchasing
                                        or otherwise, the Creative hands of India indicates your agreement to the
                                        following
                                        terms and conditions.</h6>

                                    <h2 class="wp-block-heading"> Creative hands of India Terms of Use </h2>

                                    <p> “This document is an electronic record in terms of Information Technology Act,
                                        2000
                                        and rules there under as applicable and the amended provisions pertaining to
                                        electronic records in various statutes as amended by the Information Technology
                                        Act,
                                        2000. This electronic record is generated by a computer system and does not
                                        require
                                        any physical or digital signatures.
                                    </p>
                                    <p>
                                        This document is published in accordance with the provisions of Rule 3 (1) of
                                        the
                                        Information Technology (Intermediaries guidelines) Rules, 2011 that require
                                        publishing the rules and regulations, privacy policy and Terms of Use for access
                                        or
                                        usage of creative hands of india website.</p>

                                    <p> The domain name www.creativehandsof india.com (hereinafter referred to as
                                        "Website")
                                        is owned by creative hands of india ,office address 9 “Someshwar “ Harivilla Row
                                        House, opp.seema Hall 100ft Road Satelite,380015 Ahmedabad</p>

                                    <p> For the purpose of these Terms & Conditions, wherever the context so requires
                                        "You"
                                        or "User" shall mean any natural or legal person who has agreed to become a
                                        buyer on
                                        the Website by providing Registration Data, while registering on the Website as
                                        Registered User using the computer systems. Creative Hands of India allows the
                                        User
                                        to surf the Website or making purchases without registering on the Website. The
                                        term
                                        "We", "Us", "Our" shall mean Creative Hands of India</p>

                                    <p> When You use any of the services provided by us through the Website, including
                                        but
                                        not limited to (e.g. Product Reviews, Seller Reviews), You will be subject to
                                        the
                                        rules, guidelines, policies, terms, and conditions applicable to such service,
                                        and
                                        they shall be deemed to be incorporated into this Terms of Use and shall be
                                        considered as part and parcel of this Terms of Use. We reserve the right, at Our
                                        sole discretion, to change, modify, add or remove portions of these Terms of
                                        Use, at
                                        any time without any prior written notice to You. It is Your responsibility to
                                        review these Terms of Use periodically for updates / changes. Your continued use
                                        of
                                        the Website following the posting of changes will mean that You accept and agree
                                        to
                                        the revisions. As long as You comply with these Terms & Conditions, We grant You
                                        a
                                        personal, non-exclusive, non-transferable, limited privilege to enter and use
                                        the
                                        Website.
                                    </p>


                                    <h2 class="wp-block-heading">Website Use & Membership </h2>
                                    <p>
                                        Use of the Website is available only to persons who can form legally binding
                                        contracts under Indian Contract Act, 1872. Persons who are "incompetent to
                                        contract"
                                        within the meaning of the Indian Contract Act, 1872 including minors,
                                        un-discharged
                                        insolvents etc. Are not eligible to use the Website. If you are a minor i.e.
                                        Under
                                        the age of 18 years, you shall not register as a User of the Creative hands of
                                        india
                                        website and shall not transact on or use the website. As a minor if you wish to
                                        use
                                        or transact on website, such use or transaction may be made by your legal
                                        guardian
                                        or parents on the Website. Creative hands of india reserves the right to
                                        terminate
                                        your membership and / or refuse to provide you with access to the Website if it
                                        is
                                        brought to Creative hands of india ’s notice or if it is discovered that you are
                                        under the age of 18 years. </p>
                                    <p>

                                        Transaction: You will be solely responsible for keeping the required computer
                                        equipment and the internet connectivity for accessing, using and transacting on
                                        website. You will also be under the obligation of using website only for lawful
                                        and
                                        responsible purposes, and not indulging in any kind of unforeseen activity.
                                        Coupons
                                        and vouchers purchased through website should only be used for personal use and
                                        not
                                        for the purpose of resale. Website is not liable for any kind of damage or loss
                                        arising out of direct or indirect authority failure for the transactions due to
                                        the
                                        amount exceeding the predetermined limit set by Website in association with the
                                        banks. Registration & Login credentials: If you use the Website, you shall be
                                        responsible for maintaining the confidentiality of your Display Name and
                                        Password
                                        and you shall be responsible for all activities that occur under your Display
                                        Name
                                        and Password. You agree that if You provide any information that is untrue,
                                        inaccurate, not current or incomplete or We have reasonable grounds to suspect
                                        that
                                        such information is untrue, inaccurate, not current or incomplete, or not in
                                        accordance with the this Terms & Conditions, We shall have the right to
                                        indefinitely
                                        suspend or terminate or block access of your membership on the Website and
                                        refuse to
                                        provide you with access to the Website. Communications: When you use the Website
                                        or
                                        send emails or other data, information or communication to us, you agree and
                                        understand that you are communicating with Us through electronic records and
                                        your
                                        consent to receive communications via electronic records from us periodically
                                        and as
                                        and when required. We may communicate with you by email or by such other mode of
                                        communication, electronic or otherwise.
                                        Terms of Service </p>
                                    <p>
                                        Welcome to Creative Hands of India! By signing up for a Creative Hands of India
                                        Account or by using any Creative Hands of India Services (as defined below), you
                                        are
                                        agreeing to be bound by the following terms and conditions (the “Terms of
                                        Service”).
                                        As used in these Terms of Service, “we”, “us”, “our” and “Creative Hands of
                                        India”
                                        means the applicable Creative Hands of India Contracting Party , and “you” means
                                        the
                                        Creative Hands of India User (if registering for or using a Creative Hands of
                                        India
                                        Service as an individual), or the business employing the Creative Hands of India
                                        User (if registering for or using a Creative Hands of India Service as a
                                        business)
                                        and any of its affiliates.
                                    </p>
                                    <p>
                                        The services offered by Creative Hands of India under these Terms of Service
                                        include
                                        various products and services that enable you to build your own Account and help
                                        you
                                        to sell goods and services to customers, whether online (“Online Services”), in
                                        person (“POS Services”), or both. Any such service or services offered by
                                        Creative
                                        Hands of India are referred to in these Terms of Services as the “Service(s)”.
                                        Any
                                        new features or tools which are added to the current Services will also be
                                        subject
                                        to the Terms of Service. You can review the current version of the Terms of
                                        Service
                                        at any time at our site. </p>
                                    <p>
                                        You must read, agree with and accept all of the terms and conditions contained
                                        or
                                        expressly referenced in these Terms of Service, including Creative Hands of
                                        India’s
                                        Acceptable Use Policy (“AUP”) and Privacy Policy, and, if applicable, the
                                        Supplementary Terms of Service for E.U. Merchants ("EU Terms"), the Creative
                                        Hands
                                        of India API License and Terms of Use (“API Terms”) and the Creative Hands of
                                        India
                                        Data Processing Addendum (“DPA”) before you may sign up for a Creative Hands of
                                        India Account or use any Creative Hands of India Service. </p>
                                    <p>
                                        Everyday language summaries are provided for convenience only and appear in bold
                                        near each section, but these summaries are not legally binding. Please read the
                                        Terms of Service, including any document referred to in these Terms of Service,
                                        for
                                        the complete picture of your legal requirements. By using Creative Hands of
                                        India or
                                        any Creative Hands of India services, you are agreeing to these terms. Be sure
                                        to
                                        occasionally check back for updates. </p>
                                    <h2 class="wp-block-heading"> 1.Account Terms </h2>
                                    <p>
                                        To access and use the Services, you must register for a Creative Hands of India
                                        account (“Account”). To complete your Account registration, you must provide us
                                        with
                                        your full legal name, business address, phone number, a valid email address, and
                                        any
                                        other information indicated as required. Creative Hands of India may reject your
                                        application for an Account, or cancel an existing Account, for any reason, at
                                        our
                                        sole discretion. </p>
                                    <p>
                                        You confirm that you are receiving any Services provided by Creative Hands of
                                        India
                                        for the purposes of carrying on a business activity and not for any personal,
                                        household or family purpose.
                                        You acknowledge that Creative Hands of India will use the email address you
                                        provide
                                        on opening an Account or as updated by you from time to time as the primary
                                        method
                                        for communication with you (“Primary Email Address”). You must monitor the
                                        Primary
                                        Email Address you provide to Creative Hands of India and your Primary Email
                                        Address
                                        must be capable of both sending and receiving messages. Your email
                                        communications
                                        with Creative Hands of India can only be authenticated if they come from your
                                        Primary Email Address. </p>
                                    <p>
                                        You are responsible for keeping your password secure. Creative Hands of India
                                        cannot
                                        and will not be liable for any loss or damage from your failure to maintain the
                                        security of your Account and password.
                                        Technical support in respect of the Services is only provided to Creative Hands
                                        of
                                        India Users. Questions about the Terms of Service should be sent to Creative
                                        Hands
                                        of India Support. </p>
                                    <p>
                                        You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion
                                        of
                                        the Service, use of the Services, or access to the Services without the express
                                        written permission by Creative Hands of India.
                                        You agree not to work around, bypass, or circumvent any of the technical
                                        limitations
                                        of the Services, use any tool to enable features or functionalities that are
                                        otherwise disabled in the Services, or decompile, disassemble or otherwise
                                        reverse
                                        engineer the Services. </p>
                                    <p>
                                        You agree not to access the Services or monitor any material or information from
                                        the
                                        Services using any robot, spider, scraper, or other automated means.
                                        You understand that your Materials may be transferred unencrypted and involve
                                        (a)
                                        transmissions over various networks; and (b) changes to conform and adapt to
                                        technical requirements of connecting networks or devices. “Materials” means Your
                                        Trademarks, copyright content, any products or services you sell through the
                                        Services (including description and price), and any photos, images, videos,
                                        graphics, written content, audio files, code, information, or other data
                                        provided or
                                        made available by you or your affiliates to Creative Hands of India or its
                                        affiliates.</p>
                                    <p>
                                        Which means
                                        You are responsible for your Account, the Materials you upload to the Creative
                                        Hands
                                        of India Service and the operation of your Creative Hands of India Store. If you
                                        violate Creative Hands of India’s terms of service we may cancel your service
                                        access. If we need to reach you, we will communicate via the Primary Email
                                        Address.</p>
                                    <h2 class="wp-block-heading"> 2. Creative Hands of India Rights </h2>
                                    <p>
                                        The Services have a range of features and functionalities. Not all Services or
                                        features will be available to all Merchants at all times and we are under no
                                        obligation to make any Services or features available in any jurisdiction.
                                        Except
                                        where prohibited in these Terms of Service or by applicable law, we reserve the
                                        right to modify the Services or any part thereof for any reason, without notice
                                        and
                                        at any time.
                                    </p>
                                    <p>
                                        Creative hands of India does not pre-screen Materials and it is in our sole
                                        discretion to refuse or remove any Materials from any part of the Services,
                                        including if we determine in our sole discretion that the goods or services that
                                        you
                                        offer through the Services, or the Materials uploaded or posted to the Services,
                                        violate our AUP or these Terms of Service.
                                        Verbal or written abuse of any kind (including threats of abuse or retribution)
                                        of
                                        any Creative hands of India member, or officer will result in immediate Account
                                        termination.</p>
                                    <p>
                                        We reserve the right to provide our Services to your competitors and make no
                                        promise
                                        of exclusivity. You further acknowledge and agree that Creative hands of India
                                        members that they may compete with you, although they may not use your
                                        Confidential
                                        Information in doing so.
                                        In the event of a dispute regarding Account ownership, we reserve the right to
                                        request documentation to determine or confirm Account ownership.
                                        Creative Hands of India reserves the right to determine, in our sole discretion,
                                        rightful Account ownership and transfer an Account to the rightful Account
                                        Owner. If
                                        we are unable to reasonably determine the rightful Account Owner, without
                                        prejudice
                                        to our other rights and remedies, Creative Hands of India reserves the right to
                                        temporarily suspend or disable an Account until resolution has been determined
                                        between the disputing parties.
                                    </p>
                                    <p>
                                        Which means
                                        Creative Hands of India has the right to control who we make our Services
                                        available
                                        to and we can modify them at any time. We also have the right to refuse or
                                        remove
                                        Materials from any part of the Services, including your Store. We may offer our
                                        services to your competitors, but we will never share your confidential
                                        information
                                        with them in doing so. In the event of an ownership dispute over a Creative
                                        Hands of
                                        India Account, we can freeze a Creative Hands of India Account or transfer it to
                                        the
                                        rightful owner, as determined by us.
                                    <h2 class="wp-block-heading"> 3. Your Responsibilities </h2>
                                    <p>
                                        You acknowledge and agree to provide public-facing contact information, a refund
                                        policy and order fulfillment timelines on your Creative Hands of India website
                                        You acknowledge and agree that the Services are not a marketplace, and any
                                        contract
                                        of sale made through the Services is directly between you and the customer. You
                                        are
                                        the seller of record for all items you sell through the Services. You are
                                        responsible for the creation and operation of your Creative Hands of India
                                        account ,
                                        your Materials, the goods and services that you may sell through the Services,
                                        and
                                        all aspects of the transactions between you and your customer(s). This includes,
                                        but
                                    </p>
                                    <p>
                                        is not limited to, authorizing the charge to the customer in respect of the
                                        customer’s purchase, refunds, returns, fulfilling any sales or customer service,
                                        fraudulent transactions, required legal disclosures, regulatory compliance,
                                        alleged
                                        or actual violation of applicable laws (including but not limited to consumer
                                        protection laws in any jurisdiction where you offer products or services for
                                        sale),
                                        or your breach of these Terms of Service. You represent and warrant that your
                                        Store,
                                        your Materials and the goods and services you sell through the Services will be
                                        true, accurate, and complete, and will not violate any applicable laws,
                                        regulations
                                        or rights of third parties. For the avoidance of doubt, Creative Hands of India
                                        will
                                        not be the seller or merchant or record and will have no responsibility for your
                                        account or items sold to customers through the Services.
                                        You are solely responsible for the goods or services that you may sell through
                                        the
                                        Services (including description, price, fees, tax that you calculate, defects,
                                        required legal disclosures, regulatory compliance, offers or promotional
                                        content),
                                        including compliance with any applicable laws or regulations.
                                        You may not use the Creative Hands of India Services for any illegal or
                                        unauthorized
                                        purpose nor may you, in the use of the Service, violate any laws in your
                                        jurisdiction (including but not limited to copyright laws), the laws applicable
                                        to
                                        you in your customer’s jurisdiction, or the laws of India and the Province of
                                        Gujarat. You will comply with all applicable laws, rules and regulations
                                        (including
                                        but not limited to obtaining and complying with the requirements of any license
                                        or
                                        permit that may be necessary to operate your Account or that may be held by you)
                                        in
                                        your use of the Service and your performance of obligations under the Terms of
                                        Service.
                                    </p>
                                    <p>
                                        The API Terms govern your access to and use of the Creative Hands of India API
                                        (as
                                        defined therein). You are solely responsible for the activity that occurs using
                                        your
                                        API Credentials (as defined in the API Terms) and for keeping your API
                                        Credentials
                                        secure. </p>
                                    <p> Which means
                                        You are responsible for your Creative Hands of India Store, the goods or
                                        services
                                        you sell, and your relationship with your customers, not us. If you access the
                                        Creative Hands of India API, your use of the Creative Hands of India API is
                                        subject
                                        to the API Terms. </p>
                                    <h2 class="wp-block-heading"> 4.Confidentiality </h2>
                                    <p> “Confidential Information” will include, but will not be limited to, any and all
                                        information associated with a party’s business and not publicly known, including
                                        specific business information, technical processes and formulas, software,
                                        customer</p>
                                    <p> lists, prospective customer lists, names, addresses and other information
                                        regarding
                                        customers and prospective customers, product designs, sales, costs (including
                                        any
                                        relevant processing fees), price lists, and other unpublished financial
                                        information,
                                        business plans and marketing data, and any other confidential and proprietary
                                        information, whether or not marked as confidential or proprietary. Creative
                                        Hands of
                                        India’s Confidential Information includes all information that you receive
                                        relating
                                        to us, or to the Services, that is not known to the general public including
                                        information related to our security program and practices. </p>

                                    <p> Which means
                                        You agree to use the Confidential Information of the other only to perform the
                                        obligations in these Terms of Service. Confidential Information must be
                                        protected
                                        and respected.
                                    <h2 class="wp-block-heading">5.Privacy and Data Protection </h2>
                                    <p>
                                        Creative Hands of India’s use and collection of personal information is governed
                                        by
                                        our Privacy Policy. Additionally, if you or your customers are located in
                                        Europe,
                                        Creative Hands of India’s use and collection of European personal information is
                                        further governed by our Data Processing Addendum.
                                    </p>
                                    <h2 class="wp-block-heading"> 6. Intellectual Property and Your Material </h2>
                                    <p>
                                        Anything you upload remains yours (if it was yours) and is your responsibility,
                                        but
                                        Creative Hands can use and publish the things you upload. Anything uploaded to
                                        Creative Hands remains the property and responsibility of its initial owner.
                                        However, Creative Hands will receive a license of materials published through
                                        our
                                        platform that we may use to operate and promote our Services
                                        The Website is a sales channel that is only available to Eligible online and
                                        will
                                        display Materials from our Website. If you do not wish for your Materials to be
                                        available in the website, it is your responsibility to manage or deactivate this
                                        Service.
                                    </p>
                                    <h2 class="wp-block-heading"> 7. Modifications </h2>

                                    <p> If we make a material change to the Terms of Service that adversely affects your
                                        rights under the Terms of Service or your use of our Services in a material way,
                                        we
                                        will notify you in advance (unless the change relates to legal requirements or
                                        to
                                        prevent abuse of our Services, among other things). </p>
                                    <h2 class="wp-block-heading"> 8.Feedback and Reviews </h2>
                                    <p>
                                        We welcome customer feedback but are under no obligation to ensure that ideas
                                        and
                                        suggestions regarding our Services or the services of third parties remain
                                        confidential and we can use the feedback in any way we want.
                                    </p>
                                    <h2 class="wp-block-heading">
                                        9. Limitation of Liability and Indemnification </h2>
                                    <p>
                                        We are not responsible for damages or lawsuits that arise if you break the law,
                                        breach this agreement or go against the rights of a third party. The Service is
                                        provided on an “as is” and “as available” basis. We provide no warranties and
                                        our
                                        liability is limited in the event of errors or interruptions.
                                        10.Third Party Services, Experts, and Experts Marketplace
                                        We are not responsible for third party services, so use them at your own risk.
                                        If
                                        you choose to use Third Party Services on the Creative Hands Of India platform,
                                        you
                                        consent to us sharing your data (and potentially the data of your Customers) to
                                        those services. If you use Third Party Services you agree that we do not provide
                                        a
                                        warranty, so get advice beforehand. </p>




                                </div>
                            </article>
                       
                    </div>
                </div>
    </section>
</main>